apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: cakephp-mysql-persistent
    template: cakephp-mysql-persistent
  name: {{ .Values.database_service_name }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volume_capacity }}
