application_domain: '# TODO: must define a default value for .application_domain'
cakephp_secret_token: '# TODO: must define a default value for .cakephp_secret_token'
cakephp_security_salt: '# TODO: must define a default value for .cakephp_security_salt'
composer_mirror: '# TODO: must define a default value for .composer_mirror'
context_dir: '# TODO: must define a default value for .context_dir'
database_name: default
database_password: '# TODO: must define a default value for .database_password'
database_service_name: mysql
database_user: cakephp
github_webhook_secret: '# TODO: must define a default value for .github_webhook_secret'
memory_limit: 512Mi
memory_mysql_limit: 512Mi
mysql_default_authentication_plugin: mysql_native_password
mysql_version: 8.0-el8
name: cakephp-mysql-persistent
namespace: openshift
opcache_revalidate_freq: "2"
php_version: 8.1-ubi9
source_repository_ref: '# TODO: must define a default value for .source_repository_ref'
source_repository_url: https://github.com/sclorg/cakephp-ex.git
volume_capacity: 1Gi
