description: |-
  PostgreSQL database service, with persistent storage. For more information about using this template, including OpenShift considerations, see https://github.com/sclorg/postgresql-container/.

  NOTE: Scaling to more than one replica is not supported. You must have persistent volumes available in your cluster to use this template.
name: postgresql-persistent
tags: database,postgresql
sources:
  - https://github.com/sclorg/helm-charts
version: v0.0.1
